FROM python:3.9-alpine

WORKDIR /var/lib/benchmark

COPY benchmark-scripts/ann/requirements.txt /var/lib/benchmark/requirements.txt

RUN apk update && \
    apk add --no-cache make automake gcc g++ curl python3-dev py3-numpy hdf5-dev go && \
    ln -sf python3 /usr/bin/python && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip install --no-cache-dir --upgrade pip setuptools && \
    pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

COPY ./benchmarker /var/lib/benchmark/
RUN go build -o benchmarker .

CMD [ "python", "./benchmark.py" ]

# Copy benchmarking scripts last, so that when parameters are changed, the rest
# can be taken from cache
COPY benchmark-scripts/ann/benchmark.py /var/lib/benchmark/benchmark.py
COPY benchmark-scripts/src/functions.py /var/lib/benchmark/functions.py

